# -*- coding:utf-8 -*-

from saklient.errors.httpconflictexception import HttpConflictException
from saklient.errors.httpconflictexception import HttpConflictException

# module saklient.cloud.errors.ftpisalreadyopenexception

class FtpIsAlreadyOpenException(HttpConflictException):
    ## 要求された操作を行えません。FTP共有は既に開始されています。
    
    # (class field) default_message = "要求された操作を行えません。FTP共有は既に開始されています。"
    
    pass
