# -*- coding:utf-8 -*-

from saklient.errors.httpserviceunavailableexception import HttpServiceUnavailableException
from saklient.errors.httpserviceunavailableexception import HttpServiceUnavailableException

# module saklient.cloud.errors.operationfailureexception

class OperationFailureException(HttpServiceUnavailableException):
    ## サービスが利用できません。操作に失敗しました。サーバが混雑している可能性があります。
    
    # (class field) default_message = "サービスが利用できません。操作に失敗しました。サーバが混雑している可能性があります。"
    
    pass
