# -*- coding:utf-8 -*-

from saklient.errors.httpconflictexception import HttpConflictException
from saklient.errors.httpconflictexception import HttpConflictException

# module saklient.cloud.errors.runoutofipaddressexception

class RunOutOfIpAddressException(HttpConflictException):
    ## 要求された操作を行えません。指定されたネットワークに属するIPアドレスはすべて使用中です。
    
    # (class field) default_message = "要求された操作を行えません。指定されたネットワークに属するIPアドレスはすべて使用中です。"
    
    pass
